### ISSUE TITLE
Meglio aver paura che buscarne

### ISSUE THREAD

**Issue by notthatred** [unhorsing/ways-of-saying#72] opened 2016-10-11 13:17 UTC
"Better to have fear than to be beaten up"

**Comment by m4ng0** [comment] 2016-10-12 06:05
Good! Let's wait for another opinion from the Great Council, then we can proceed for inclusion.

**Comment by gpini** [comment] 2016-10-13 10:51
This is a duplicate of issue #43

**Comment by m4ng0** [comment] 2016-10-13 16:20
Good point!

**Closed as completed by m4ng0** 2016-10-13 16:20 UTC
